### ISSUE TITLE
[BUG] Compatibility with Quick Status Select

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/monks-little-details#194]
Quick Status Select is a mod that adds a search bar (automatically focused) on top of Token HUD Condition list and allows you to filter conditions by first few letters of their names. https://github.com/jeremiahverba/qss

With V10 and recent versions, using that mod to filter the conditions list causes a CSS issue where the results would be stuck into each other, an issue with vertical margins between the objects. I tried to fix it with margin-bottom: 50px but then it breaks the non-filtered list.

![image](https://user-images.githubusercontent.com/4083812/190031878-bb3e7f31-f583-4adc-89a1-cb51dcbac533.png)

![image](https://user-images.githubusercontent.com/4083812/190031951-e06e3e15-71ab-4b21-8dfe-2a2172aa20aa.png)

![image](https://user-images.githubusercontent.com/4083812/190031850-5268b325-9e3b-4607-a290-0a34dc47dcd7.png)

Perhaps you could look into the issue or maybe add the QSS functionality to Little Details because QSS has not been updated from V8 days and it is starting to age, and could use a great developer to provide such important feature.

**Comment by ironmonk88** [comment]
This only affects when the statuses are sorted into columns because Little Details has to calculate the percent height by the number of visible entries.  Quick Settings changes that value so the percent height is no longer accurate.

There's not much I can do about it on my end.  But I'd suggest that Quick Status Select instead uses `visibility: hidden` or 'opacity: 0.1` instead of fully hiding the status.

**Comment by ironmonk88** [comment]
Closing this as there's not much that I can do about it.
The issue lies with the Quick Status Select module.
