### ISSUE TITLE
1.0.17 hotkeys

### ISSUE THREAD

**Issue by LamahHerder** [ironmonk88/monks-little-details#34]
T is for Target is incompatible and I would imagine anything else that uses hotkeys will cause same issue

Took me a while to figure out what changed
First had to find which module was conflicting (luckily Find the Culprit helps)
Then when I disable the feature it only applies after app reload/refresh

All fixed now, but others may run into this issue with same module or different module and not be able to fix or figure it out

Ideas to avoid conflict:
1 - Notification that Monks tools is using these buttons when people install/upgrade to this version
2 - Force reload when the checkmark is removed for this feature
3 - Default to having feature off
4 - Use https://foundryvtt.com/packages/lib-df-hotkeys

`Adding the option to briefly switch between layers by holding down a key and pressing Shift+key will change the layer. This should let you switch briefly to another layer such as the Tiles layer to hide or show a tile before releasing the key and going back tot he token layer. Current keys are assigned as r=tokens, t-tiles, y-lighting, u-sounds, i-terrain (if you have the Terrain Layer module installed)`

**Comment by ironmonk88** [comment]
Yeah, I think this went out sooner than it was supposed to.
Should be fixed now.  Switched to using Library DF Hotkeys.  And a different set of keys.  Although... who knows what the new ones will conflict with.  At least with the Library they can be changed.
And setting the feature to off.
Also going to look into showing a display page if anything new gets added to Little Details, instead of surprising it on people.
