### ISSUE TITLE
Implement german language

### ISSUE THREAD

**Issue by ThoGri75** [ironmonk88/monks-little-details#42]
Hello,

how can I use a german json?

regards
ThoGri

**Comment by ironmonk88** [comment]
There's an easy way and a nice way.  I'll take either.
The easy way is to grab a copy of the en.json and rename it de.json.  Then translate all the English phrases to German and attach the file to a comment in this thread.

The nice way is to fork a copy of the entire project, add the de.json to your copy of the project and update the module.json to include German.  Then submit it as a merge request.  This way is nicer because if there are any changes in the future to the en.json file, then you can update and push the new changes.

I'll take whatever is easier for you.  :-)  I'm just happy to have a German translation.

**Comment by ironmonk88** [comment]
Closing this as German language should be a merge request.
