### ISSUE TITLE
[FEATURE REQUEST] Disable audio for all players

### ISSUE THREAD

**Issue by DarKDinDoN** [ironmonk88/monks-little-details#81]
Hello,

Can you add a GM setting that disable all module sounds for all players?
I know that players can individually disable sound, but the issue with that is that the more module with user settings, the more configuration I need to ask all players to do.

**Comment by ironmonk88** [comment]
Sorry for taking so long to get back to this.
I'm cancelling the ticket only because there are other options.

There's a module, [Socket Settings](https://foundryvtt.com/packages/SocketSettings), that will let you update your players settings.

Monk's Little Details is already heavy with settings, and I'd like to avoid adding another one.  And SocketSettings gives you more control over the players settings than Little Details could.
