### ISSUE TITLE
Hide Enemies breaks Hidden Initiative Module

### ISSUE THREAD

**Issue by Tupsi** [ironmonk88/monks-little-details#89]
Topic says it all, if you have both "Monks little details" and "Hidden Initiative" active plus the MLD Option "Hide Enemies" from the Combat Tracker section, the other module gets ignored and you see the initivative numbers again instead of the ?.

Not sure if there is a way around that for you, but I thought I let you know, as it took me some clicking to figure out what was causing it :-)

Steps to repeat:
1) install and activate MLD
2) install and activate Hidden Initiative (https://github.com/sfuqua/fvtt-hidden-initiative)
3) Enable "Hide Enemies" in MLD Settings in the Combat Tracker section
4) Start a combat
5) watch all PC and NPCs have visible initiative numbers in combat tracker (instead of a ?)

**Comment by ironmonk88** [comment]
Fixed in the latest release.
Hidden Initiatives is not playing nicely with it's code.  It takes control of the getData function making it really hard to share with other modules.  Little Details was doing the same thing to make sure it could do what it needed to do, and ended up preventing Hidden Initiative from running it's code.

I did my best to work around it.
