### ISSUE TITLE
Bloodsplats behind actors

### ISSUE THREAD

**Issue by Nedrapter** [ironmonk88/monks-little-details#96]
Having the bloodsplat in front of the player tokens that might stand on the corpse's square makes them look akward and hides them. Would be very appreciated if bloodsplats go behind any token above them that is not dead.

**Comment by ironmonk88** [comment]
I keep coming back to this one... but I think I'm going to label it as will not fix.

Reason being that bloodsplats will go under a token that has been moved on top of a "dead" token.  They'll only appear above a token if the "dead" token is the last one to move.  And I think it would get really annoying if you're trying to move the dead token and release it too early, only to find that you can no longer grab it because it's under an active token and you have to move the active token to the side to get back to it.

There's another module called Cycle Stack that will let you keep clicking on a stack of tokens to cycle through them and I think in combination with that you can drop the bloodsplats underneath a current token.  I'd just rather not do it automatically if it's not something you were intending to do.

**Comment by ironmonk88** [comment]
Closing this while cleaning up tickets.  I think changes in Foundry have been better about where in the order a token sits, and my original reservations remain.
